### ISSUE TITLE
Kill module limitations and MITM limitation/bug

### ISSUE THREAD

**Issue by xxskorpion88xx** [cSploit/cSploit.github.io#12]
Kill module is restricted to single target now.
It is nomore avable against whole network.

MiMT sessione is unclickable if you select a WiFi target

Ver. 1.6.3 bugfixed for KitKat (last)
Nexus 4 Marshmallow 6.0.1 Chroma hellcore kernel

On previously version of d .sploit all works. I never joined Z A nti and still I'm using old versions.

**Comment by DominikTV** [comment]
You are on the wrong place here, for android specific issues please go [here](https://github.com/cSploit/android)
