### ISSUE TITLE
Contributors page??

### ISSUE THREAD

**Issue by DeveloppSoft** [cSploit/cSploit.github.io#17]
Hey guys, what about adding a page with a list of evry peoples working on cSploit?
We may add our websites etc...
So peoples will be able to see how much we are on that project :smirk:

**Comment by DominikTV** [comment]
Good idea, if someone have any ideas for a layout or anything else, post it here. I'll also take some notes when I have some time :smiley:

**Comment by DeveloppSoft** [comment]
Well... I think we might use something like the following:
# Bob

## Teams / roles
- issues maintainer
- tester

## Site and personal things
- bob.example.org
- BTC: HJKJDEHKSSRIII
- etc

But that's just an idea...

**Comment by DeveloppSoft** [comment]
Outdated.
