### ISSUE TITLE
Can't install gems (cannot start process)

### ISSUE THREAD

**Issue by technocookiejar** [cSploit/cSploit.github.io#5]
Hello tux-mind,

I experience problems while installing csploit, I have a Galaxy S5 running on Android 5.0.
When I open it, it says Install Core, I installed it, then it says Install Ruby and after it has extracted, it cannot start the process but then it proceeds to ask me to install the MSF which fails after the "installing gems dialog"
Attached you can find the log file

Looking forward to finding a solution because csploit is a really cool network tool

Here is the logcat file: https://gist.github.com/technocookiejar/ae68b1417832dfd89844/e72fc69c9aeb8d55542c47e378d9790e06c1095a

Nice regards :)

**Comment by tux-mind** [comment]
@technocookiejar post issues in the right place please.

btw that problem has been recently fixed in cSploit.
