### ISSUE TITLE
New website

### ISSUE THREAD

**Issue by DominikTV** [cSploit/cSploit.github.io#6]
Hey there,

I've done a new layout/website for csploit.org and wanted to show it to you.
You can find it [here](http://www.dominiktv.net/cs/).
Its not completely finished and the text was 1:1 copied, but I think the result is still fine and looks cool :)

**Comment by TheMcSebi** [comment]
Also it looks very nice on mobile phones! Good job.

**Comment by fabinhojcr** [comment]
Good job, the site is getting interesting.

**Comment by DeveloppSoft** [comment]
Really good, waiting to know what @tux-mind think

**Comment by DeveloppSoft** [comment]
Y ou might start by creating a pull request

**Comment by DominikTV** [comment]
I created a new project: https://github.com/DominikTV/cSploit-Website-2

**Comment by tux-mind** [comment]
@DominikTV thanks so much for your help.

sadly Github isn't a web host and will not execute php code.
I have to purchase some hosting space to use your website.

I'll convert your php-website to a jekyll one, thus to host it for free on github.
just make me a collaborator of your repo, I'll work on a separate branch, leaving you able to finish all your stuff and merge our work together when we're done.

I'll start working on your clean and awesome version of the cSploit website as I fix the MSF :blush:

**Comment by tux-mind** [comment]
@DominikTV forgive me, don't add me as collaborator.

porting your website into the existing one is faster.
just  let me known when you think that you have completed the website layout and I'll start working on it.

I will make you able to manage the website when the porting is done :wink:

**Comment by DominikTV** [comment]
@tux-mind I could also write the whole website in HTML, I used PHP only to include some files (like header etc...), so it shouldn't be a big deal :)

**Comment by tux-mind** [comment]
PHP is fine, is more near to Ruby than html ;)
Il 07/set/2015 12:55 PM, "Dominik" <notifications@github.com> ha scritto:

**Comment by DominikTV** [comment]
So, here is the finished website: https://github.com/DominikTV/cSploit-website

But I would recommend to host the page on a "real" web space (I got one if that is the problem ;) )
And if you want I can also create relevant news pages, then you have nothing to convert to ruby :)

**Comment by DeveloppSoft** [comment]
Good work !
Maybe @tux-mind will add you to the team, personnaly I think that you
should be a part of it.

**Comment by DominikTV** [comment]
Would be great :+1: 
I like to help where I can :)

**Comment by DominikTV** [comment]
Note: Preview uploaded at http://www.dominiktv.net/cs/

**Comment by tux-mind** [comment]
@DominikTV I sent you an invitation to join into the web developers team.

just let me try convert it into jekyll, just to not have to write HTML for every news we will publish :sweat_smile: 

thanks for all your efforts :heart:

**Comment by tux-mind** [comment]
@DominikTV seems that you forgot `css/style.css` :wink:

**Comment by DominikTV** [comment]
@tux-mind Sure it's down? http://www.dominiktv.net/cs/ works perfect for me and my friends :)

Year, I forgot to delete `css/style.css`, thanks for that :wink:

**Comment by tux-mind** [comment]
@DominikTV you're right... I cannot connect form my mobile connection, but using a proxy or my VPN I can see it correctly... strange...

working on it.

**Comment by DeveloppSoft** [comment]
@DominikTV really good, maybe I will need to take some courses...

**Comment by tux-mind** [comment]
done.
donation buttons need to be fixed.

thanks for this sweet UI @DominikTV :blush:

**Comment by DominikTV** [comment]
@tux-mind No problem :smile:
